title: Subdomain Scanner
description: Scan subdomains using RapidAPI
theme: minimal-mistakes-jekyll
skin: dark
plugins:
  - jekyll-feed
  - minimal-mistakes-jekyll

minimal_mistakes_skin: "air"
markdown: kramdown
